[package]
name = "namecom_ddns"
version = "0.1.1"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
gip = "0.7"
log = "0.4"
pnet = "0.28"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.10"
strum = { version = "0.21", features = ["derive"] }
strum_macros = "0.21"
subprocess = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.10", features = ["macros", "rt-multi-thread", "sync", "time"] }
toml = "0.5"
