name: Build Releases

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Setup Cargo
      run: |
          cargo install --locked --force --path
          cargo update

    - name: Build release
      run: cargo build --release

    - name: Remove interferring files
      run: bash -c "rm -rf target/release/namecom_ddns.d"

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: namecom_ddns-${{ matrix.config.name }}
        path: target/release/namecom_ddns*
