name: Rust

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: macOS_Intel
          os: macos-latest
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run lints
      run: cargo clippy -- -D warnings --verbose
    - name: Run integration test
      if: startswith( matrix.config.os, 'macos' ) || startswith( matrix.config.os, 'ubuntu' )
      env:
        TEST_NAMECOM_URL: ${{ secrets.TEST_NAMECOM_URL }}
        TEST_NAMECOM_HOST: ${{ secrets.TEST_NAMECOM_HOST }}-${{ matrix.config.name }}
        TEST_NAMECOM_ZONE: ${{ secrets.TEST_NAMECOM_ZONE }}
        TEST_NAMECOM_USER: ${{ secrets.TEST_NAMECOM_USER }}
        TEST_NAMECOM_KEY: ${{ secrets.TEST_NAMECOM_KEY }}
      run: |
        ci/gen_config.sh
        cargo run -- -sf ci_config.toml -l debug
        rm ci_config.toml
        ci/validate_and_cleanup.sh
    - name: Build release
      run: cargo build --release
    - run: rm target/release/namecom_ddns.d
    - name: Upload binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: namecom_ddns-${{ matrix.config.name }}
        path: target/release/namecom_ddns*
